# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/index
    controller: App\Controller\LuckyController::number
    
app_formation:
    path: /create/formation
    controller: App\Controller\LuckyController::Formation

#https://symphony-paulobouriez.c9users.io/my_cv/public/index.php/lucky/index